### ISSUE TITLE
Convert PACT file to OAS 3.0 file

### ISSUE THREAD

**Issue by brad-jones** [pact-foundation/pact-specification#98]
I'd like to be able to convert a verified PACT file to an OAS 3.0 file/specification for the provider.
Does such tooling exist? I haven't found anything yet.

I have an interesting problem, let me explain.

In my case I have this old school .NET Framework monolith that does actually generate a Swagger spec but it's implemented poorly & ultimately the spec doesn't match reality, which is almost worse than having nothing. Anyway, solving the root problem & making the spec accurate is way too large a task to take on with 100's of endpoints to fix.

The end goal is to provide a cut down but accurate spec for this monolith that can then be used with modern OAS 3.0 tooling to generate clients, etc. Then all teams that depend on this shared code base have something reliable to reference. At the moment each team that integrates with this legacy system ultimately ends up going through this same painful experience to reverse engineer the API spec. 

I had the novel idea to write some PACT contract tests against the monolith & then convert the resulting verified PACT file into an OAS 3.0 spec.

**Comment by YOU54F** [comment]
Whilst it is possible with open-source tooling, they are many, many caveats.

You can indirectly generate an OAS from a pact file, with 

Libraries

- pmpact - https://github.com/ITV/pmpact
- postman2openapi - https://github.com/kevinswiber/postman2openapi
- postman-to-openapi - https://github.com/joolfe/postman-to-openapi

pact to a postman collection -> postman collection to an openapi spec

option 1

`cargo install postman2openapi --bin --features binary`
`npx -y pmpact https://gist.githubusercontent.com/YOU54F/994b85ff830ed2f6f21057779c0a40f0/raw/41d3286503714bca5914df7da54a665c83a84c60/pact.json  | postman2openapi`

option 2

this cannot deal with no `body` property, so this pact has been amended to use `body:{}` for the 404 case in order for this to generate (an incorrect OAS spec)

npx -y pmpact https://gist.githubusercontent.com/YOU54F/994b85ff830ed2f6f21057779c0a40f0/raw/5665d6625bc0f692f730bac058e4456c5bfe565b/pact.json > postman-collection.json && npx -y p2o postman-collection.json

>The end goal is to provide a cut down but accurate spec for this monolith that can then be used with modern OAS 3.0 tooling to generate clients

You would be better off testing the provider directly and generating a validated OAS that way, rather than indirectly via the client ( ascontract tests are not functional tests), you can see the approach shown in this example

https://github.com/pactflow/example-bi-directional-provider-postman#key-points
